# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: 
- linux
- osx

r:
- release

language: R
sudo: required
cache: packages

r_packages:
  - covr

r_github_packages: r-lib/fs

after_success:
  - Rscript -e 'library(covr); codecov()'